"""initial schema

Revision ID: 0e64fa6df16b
Revises: 
Create Date: 2026-08-01 04:16:44.948359

"""
import sqlalchemy as sa

from alembic import op

revision = '0e64fa6df16b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=True),
    sa.Column('repo', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('base_commit', sa.String(length=64), nullable=False),
    sa.Column('fail_to_pass', sa.JSON(), nullable=False),
    sa.Column('pass_to_pass', sa.JSON(), nullable=False),
    sa.Column('held_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('permission_mode', sa.String(length=24), nullable=False),
    sa.Column('topology', sa.String(length=24), nullable=False),
    sa.Column('model_tier', sa.String(length=16), nullable=False),
    sa.Column('playbook_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_contract', sa.JSON(), nullable=False),
    sa.Column('autonomy_default', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('skill_md', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('promoted_run_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('autonomy', sa.String(length=16), nullable=False),
    sa.Column('owner_resolution', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('ado_email', sa.String(length=256), nullable=True),
    sa.Column('ado_descriptor', sa.String(length=128), nullable=True),
    sa.Column('byo_pat_encrypted', sa.Text(), nullable=True),
    sa.Column('byo_pat_expires_at', sa.DateTime(), nullable=True),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ado_descriptor')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('f2p_passed', sa.Integer(), nullable=False),
    sa.Column('p2p_passed', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['eval_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_runs_case_id'), ['case_id'], unique=False)

    op.create_table('idea_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('promoted_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('trigger_description', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('source_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ado_repo_id', sa.String(length=64), nullable=True),
    sa.Column('remote_url', sa.String(length=512), nullable=False),
    sa.Column('integration_branch', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_head', sa.String(length=64), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repos_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_repos_status'), ['status'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('autonomy', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('auto_summary', sa.Text(), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('work_item_id', sa.Integer(), nullable=True),
    sa.Column('available_actions', sa.JSON(), nullable=False),
    sa.Column('session_volume_path', sa.String(length=512), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_owner_status_repo', ['created_by', 'stage', 'repo'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_stage'), ['stage'], unique=False)

    op.create_table('setup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setup_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setup_codes_user_id'), ['user_id'], unique=False)

    op.create_table('trigger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('changed_by_descriptor', sa.String(length=128), nullable=True),
    sa.Column('resolved_user_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', 'revision', name='uq_trigger_dedupe')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lane_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_run_id'), ['run_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lane_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sdk_message_uuid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_lane_seq', ['lane_id', 'seq'], unique=False)
        batch_op.create_index('ix_events_run_ts', ['run_id', 'ts'], unique=False)

    op.create_table('idea_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=8), nullable=False),
    sa.Column('author_ref', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['idea_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_comments_thread_id'), ['thread_id'], unique=False)

    op.create_table('lanes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('persona', sa.String(length=64), nullable=False),
    sa.Column('repo_scope', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('forked_from_session_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('gateway_key_alias', sa.String(length=128), nullable=True),
    sa.Column('gateway_key', sa.String(length=128), nullable=True),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lanes_run_id'), ['run_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_run_id'), ['run_id'], unique=False)

    op.create_table('pr_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('repo', sa.String(length=128), nullable=False),
    sa.Column('branch', sa.String(length=256), nullable=False),
    sa.Column('ado_pr_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('merged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['merged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr_links_run_id'), ['run_id'], unique=False)

    op.create_table('repo_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('test_cmds', sa.JSON(), nullable=False),
    sa.Column('map_version', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_table('trajectory_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lane_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_decisions', sa.JSON(), nullable=False),
    sa.Column('lessons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trajectory_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trajectory_summaries_run_id'), ['run_id'], unique=False)

    op.create_table('plan_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('success_criterion', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_steps_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_steps_plan_id'))

    op.drop_table('plan_steps')
    with op.batch_alter_table('trajectory_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trajectory_summaries_run_id'))

    op.drop_table('trajectory_summaries')
    op.drop_table('repo_profiles')
    with op.batch_alter_table('pr_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr_links_run_id'))

    op.drop_table('pr_links')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_run_id'))

    op.drop_table('plans')
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lanes_run_id'))

    op.drop_table('lanes')
    with op.batch_alter_table('idea_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_comments_thread_id'))

    op.drop_table('idea_comments')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_run_ts')
        batch_op.drop_index('ix_events_lane_seq')

    op.drop_table('events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_run_id'))

    op.drop_table('approvals')
    op.drop_table('trigger_events')
    with op.batch_alter_table('setup_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setup_codes_user_id'))

    op.drop_table('setup_codes')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_stage'))
        batch_op.drop_index('ix_runs_owner_status_repo')

    op.drop_table('runs')
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repos_status'))
        batch_op.drop_index(batch_op.f('ix_repos_name'))

    op.drop_table('repos')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('knowledge_items')
    op.drop_table('idea_threads')
    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_case_id'))

    op.drop_table('eval_runs')
    op.drop_table('deliveries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('triggers')
    op.drop_table('proposals')
    op.drop_table('playbooks')
    op.drop_table('modes')
    op.drop_table('eval_cases')
    # ### end Alembic commands ###
